# Nombre de la aplicación Spring Boot
spring.application.name=backend

# Configuración de la base de datos MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/vinylrevolution
# Nombre de usuario para acceder a la base de datos
spring.datasource.username=root
# Contraseña del usuario de la base de datos
spring.datasource.password=root
# Clase del driver JDBC de MySQL
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de Hibernate (JPA)
# Dialecto específico de MySQL para que Hibernate sepa cómo generar el SQL adecuado
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
# Permite que Hibernate cree o actualice automáticamente las tablas según las entidades JPA
spring.jpa.hibernate.ddl-auto=update
# Muestra en consola las consultas SQL generadas por Hibernate (útil para depuración)
spring.jpa.show-sql=true

# Configuración de JWT (JSON Web Token)
# Clave secreta utilizada para firmar los tokens
jwt.secret=MiClaveSuperSecretaQueDebeSerLarga
# Tiempo de expiración del token en milisegundos (aquí: 24 horas)
jwt.expirationMs=86400000

# Nivel de log para Spring Security (DEBUG permite ver información detallada sobre autenticación/autorización)
logging.level.org.springframework.security=DEBUG
